// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testpivottablewebwidget.proxies;

public class SalesOrderImport extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestPivotTableWebWidget.SalesOrderImport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		SalesOrderImport_Template("TestPivotTableWebWidget.SalesOrderImport_Template");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesOrderImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestPivotTableWebWidget.SalesOrderImport"));
	}

	protected SalesOrderImport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesOrderImportMendixObject)
	{
		super(context, salesOrderImportMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TestPivotTableWebWidget.SalesOrderImport", salesOrderImportMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestPivotTableWebWidget.SalesOrderImport");
	}

	/**
	 * @deprecated Use 'SalesOrderImport.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testpivottablewebwidget.proxies.SalesOrderImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testpivottablewebwidget.proxies.SalesOrderImport.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testpivottablewebwidget.proxies.SalesOrderImport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testpivottablewebwidget.proxies.SalesOrderImport(context, mendixObject);
	}

	public static testpivottablewebwidget.proxies.SalesOrderImport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testpivottablewebwidget.proxies.SalesOrderImport.initialize(context, mendixObject);
	}

	public static java.util.List<testpivottablewebwidget.proxies.SalesOrderImport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testpivottablewebwidget.proxies.SalesOrderImport> result = new java.util.ArrayList<testpivottablewebwidget.proxies.SalesOrderImport>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestPivotTableWebWidget.SalesOrderImport" + xpathConstraint))
			result.add(testpivottablewebwidget.proxies.SalesOrderImport.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of SalesOrderImport_Template
	 */
	public final excelimporter.proxies.Template getSalesOrderImport_Template() throws com.mendix.core.CoreException
	{
		return getSalesOrderImport_Template(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesOrderImport_Template
	 */
	public final excelimporter.proxies.Template getSalesOrderImport_Template(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		excelimporter.proxies.Template result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesOrderImport_Template.toString());
		if (identifier != null)
			result = excelimporter.proxies.Template.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesOrderImport_Template
	 * @param salesorderimport_template
	 */
	public final void setSalesOrderImport_Template(excelimporter.proxies.Template salesorderimport_template)
	{
		setSalesOrderImport_Template(getContext(), salesorderimport_template);
	}

	/**
	 * Set value of SalesOrderImport_Template
	 * @param context
	 * @param salesorderimport_template
	 */
	public final void setSalesOrderImport_Template(com.mendix.systemwideinterfaces.core.IContext context, excelimporter.proxies.Template salesorderimport_template)
	{
		if (salesorderimport_template == null)
			getMendixObject().setValue(context, MemberNames.SalesOrderImport_Template.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesOrderImport_Template.toString(), salesorderimport_template.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testpivottablewebwidget.proxies.SalesOrderImport that = (testpivottablewebwidget.proxies.SalesOrderImport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestPivotTableWebWidget.SalesOrderImport";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
