// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class SalesOrder
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.SalesOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Region("Region"),
		OrderDate("OrderDate"),
		Quantity("Quantity"),
		TotalSaleAmount("TotalSaleAmount"),
		SalesOrder_SalesRepresentative("MyFirstModule.SalesOrder_SalesRepresentative"),
		SalesOrder_Location("MyFirstModule.SalesOrder_Location"),
		SalesOrder_Customer("MyFirstModule.SalesOrder_Customer"),
		SalesOrder_Item("MyFirstModule.SalesOrder_Item");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.SalesOrder"));
	}

	protected SalesOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesOrderMendixObject)
	{
		if (salesOrderMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.SalesOrder", salesOrderMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.SalesOrder");

		this.salesOrderMendixObject = salesOrderMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SalesOrder.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.SalesOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.SalesOrder.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.SalesOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.SalesOrder(context, mendixObject);
	}

	public static myfirstmodule.proxies.SalesOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.SalesOrder.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.SalesOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.SalesOrder> result = new java.util.ArrayList<myfirstmodule.proxies.SalesOrder>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.SalesOrder" + xpathConstraint))
			result.add(myfirstmodule.proxies.SalesOrder.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Region
	 * @param region
	 */
	public final myfirstmodule.proxies.Region getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final myfirstmodule.proxies.Region getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Region.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Region.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(myfirstmodule.proxies.Region region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Region region)
	{
		if (region != null)
			getMendixObject().setValue(context, MemberNames.Region.toString(), region.toString());
		else
			getMendixObject().setValue(context, MemberNames.Region.toString(), null);
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of TotalSaleAmount
	 */
	public final java.math.BigDecimal getTotalSaleAmount()
	{
		return getTotalSaleAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalSaleAmount
	 */
	public final java.math.BigDecimal getTotalSaleAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalSaleAmount.toString());
	}

	/**
	 * Set value of TotalSaleAmount
	 * @param totalsaleamount
	 */
	public final void setTotalSaleAmount(java.math.BigDecimal totalsaleamount)
	{
		setTotalSaleAmount(getContext(), totalsaleamount);
	}

	/**
	 * Set value of TotalSaleAmount
	 * @param context
	 * @param totalsaleamount
	 */
	public final void setTotalSaleAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalsaleamount)
	{
		getMendixObject().setValue(context, MemberNames.TotalSaleAmount.toString(), totalsaleamount);
	}

	/**
	 * @return value of SalesOrder_SalesRepresentative
	 */
	public final myfirstmodule.proxies.SalesRepresentative getSalesOrder_SalesRepresentative() throws com.mendix.core.CoreException
	{
		return getSalesOrder_SalesRepresentative(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesOrder_SalesRepresentative
	 */
	public final myfirstmodule.proxies.SalesRepresentative getSalesOrder_SalesRepresentative(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.SalesRepresentative result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesOrder_SalesRepresentative.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.SalesRepresentative.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesOrder_SalesRepresentative
	 * @param salesorder_salesrepresentative
	 */
	public final void setSalesOrder_SalesRepresentative(myfirstmodule.proxies.SalesRepresentative salesorder_salesrepresentative)
	{
		setSalesOrder_SalesRepresentative(getContext(), salesorder_salesrepresentative);
	}

	/**
	 * Set value of SalesOrder_SalesRepresentative
	 * @param context
	 * @param salesorder_salesrepresentative
	 */
	public final void setSalesOrder_SalesRepresentative(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.SalesRepresentative salesorder_salesrepresentative)
	{
		if (salesorder_salesrepresentative == null)
			getMendixObject().setValue(context, MemberNames.SalesOrder_SalesRepresentative.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesOrder_SalesRepresentative.toString(), salesorder_salesrepresentative.getMendixObject().getId());
	}

	/**
	 * @return value of SalesOrder_Location
	 */
	public final myfirstmodule.proxies.Location getSalesOrder_Location() throws com.mendix.core.CoreException
	{
		return getSalesOrder_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesOrder_Location
	 */
	public final myfirstmodule.proxies.Location getSalesOrder_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesOrder_Location.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Location.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesOrder_Location
	 * @param salesorder_location
	 */
	public final void setSalesOrder_Location(myfirstmodule.proxies.Location salesorder_location)
	{
		setSalesOrder_Location(getContext(), salesorder_location);
	}

	/**
	 * Set value of SalesOrder_Location
	 * @param context
	 * @param salesorder_location
	 */
	public final void setSalesOrder_Location(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Location salesorder_location)
	{
		if (salesorder_location == null)
			getMendixObject().setValue(context, MemberNames.SalesOrder_Location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesOrder_Location.toString(), salesorder_location.getMendixObject().getId());
	}

	/**
	 * @return value of SalesOrder_Customer
	 */
	public final myfirstmodule.proxies.Customer getSalesOrder_Customer() throws com.mendix.core.CoreException
	{
		return getSalesOrder_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesOrder_Customer
	 */
	public final myfirstmodule.proxies.Customer getSalesOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesOrder_Customer.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesOrder_Customer
	 * @param salesorder_customer
	 */
	public final void setSalesOrder_Customer(myfirstmodule.proxies.Customer salesorder_customer)
	{
		setSalesOrder_Customer(getContext(), salesorder_customer);
	}

	/**
	 * Set value of SalesOrder_Customer
	 * @param context
	 * @param salesorder_customer
	 */
	public final void setSalesOrder_Customer(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Customer salesorder_customer)
	{
		if (salesorder_customer == null)
			getMendixObject().setValue(context, MemberNames.SalesOrder_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesOrder_Customer.toString(), salesorder_customer.getMendixObject().getId());
	}

	/**
	 * @return value of SalesOrder_Item
	 */
	public final myfirstmodule.proxies.Item getSalesOrder_Item() throws com.mendix.core.CoreException
	{
		return getSalesOrder_Item(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesOrder_Item
	 */
	public final myfirstmodule.proxies.Item getSalesOrder_Item(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Item result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SalesOrder_Item.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Item.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SalesOrder_Item
	 * @param salesorder_item
	 */
	public final void setSalesOrder_Item(myfirstmodule.proxies.Item salesorder_item)
	{
		setSalesOrder_Item(getContext(), salesorder_item);
	}

	/**
	 * Set value of SalesOrder_Item
	 * @param context
	 * @param salesorder_item
	 */
	public final void setSalesOrder_Item(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Item salesorder_item)
	{
		if (salesorder_item == null)
			getMendixObject().setValue(context, MemberNames.SalesOrder_Item.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SalesOrder_Item.toString(), salesorder_item.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesOrderMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.SalesOrder that = (myfirstmodule.proxies.SalesOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.SalesOrder";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
