// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_SalesOrderImport_Import(IContext context, myfirstmodule.proxies.SalesOrderImport _salesOrderImport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SalesOrderImport", _salesOrderImport == null ? null : _salesOrderImport.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SalesOrderImport_Import").withParams(params).execute(context);
	}
	public static boolean sUB_SalesOrderImport_Validate(IContext context, myfirstmodule.proxies.SalesOrderImport _salesOrderImport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SalesOrderImport", _salesOrderImport == null ? null : _salesOrderImport.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.SUB_SalesOrderImport_Validate").withParams(params).execute(context);
	}
}